
/* Loader */ 
GRANT USAGE ON DATABASE SPARCS_DEV TO ROLE SPARCS_LOADER; 
GRANT USAGE ON SCHEMA SPARCS_DEV.RAW TO ROLE SPARCS_LOADER; 

/* Transformer */
GRANT USAGE ON DATABASE SPARCS_DEV TO ROLE SPARCS_TRANSFORMER;
GRANT USAGE ON SCHEMA SPARCS_DEV.STAGING TO ROLE SPARCS_TRANSFORMER; 
GRANT USAGE ON SCHEMA SPARCS_DEV.CORE TO ROLE SPARCS_TRANSFORMER; 
GRANT USAGE ON SCHEMA SPARCS_DEV.OPS TO ROLE SPARCS_TRANSFORMER; 
/* Analyst */ 
GRANT USAGE ON DATABASE SPARCS_DEV TO ROLE SPARCS_ANALYST;
GRANT USAGE ON SCHEMA SPARCS_DEV.MART TO ROLE SPARCS_ANALYST;
