GRANT USAGE ON WAREHOUSE SPARCS_LOAD_WH TO ROLE SPARCS_LOADER; 
GRANT USAGE ON WAREHOUSE SPARCS_TRANSFORM_WH TO ROLE SPARCS_TRANSFORMER; 
GRANT USAGE ON WAREHOUSE SPARCS_BI_WH TO ROLE SPARCS_ANALYST; 
/* OPS can use transformation warehouse */ 
GRANT USAGE ON WAREHOUSE SPARCS_TRANSFORM_WH TO ROLE SPARCS_OPS; 