
CREATE RESOURCE MONITOR IF NOT EXISTS SPARCS_RESOURCE_MONITOR 
WITH CREDIT_QUOTA = 50 
FREQUENCY = MONTHLY 
START_TIMESTAMP = IMMEDIATELY 
TRIGGERS 
ON 80 PERCENT DO NOTIFY 
ON 100 PERCENT DO SUSPEND;



ALTER WAREHOUSE SPARCS_LOAD_WH SET RESOURCE_MONITOR = SPARCS_RESOURCE_MONITOR; 
ALTER WAREHOUSE SPARCS_TRANSFORM_WH SET RESOURCE_MONITOR = SPARCS_RESOURCE_MONITOR; 
ALTER WAREHOUSE SPARCS_BI_WH SET RESOURCE_MONITOR = SPARCS_RESOURCE_MONITOR;