CREATE WAREHOUSE IF NOT EXISTS SPARCS_LOAD_WH 
WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = TRUE 
COMMENT = 'SPARCS ingestion warehouse';

CREATE WAREHOUSE IF NOT EXISTS SPARCS_TRANSFORM_WH 
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = TRUE 
COMMENT = 'SPARCS transformation warehouse';


CREATE WAREHOUSE IF NOT EXISTS SPARCS_BI_WH 
WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = TRUE 
COMMENT = 'SPARCS BI and analytics warehouse';
